from datetime import datetime
from mongoengine import ( Document, StringField, DateTimeField, ListField)
import random
class Order(Document):
    customer = StringField(required=True)
    create_time = DateTimeField(default=datetime.now())
    content = StringField(required=True)
    address = StringField(required=True)
    status = StringField(default="收到訂單")
    lat = ListField(default=[random.randint(0,200),random.randint(0,200)])
    driver = StringField(default= '')
    driver_lat = ListField(default=[])
class Customer(Document):
    species = StringField(required=True)
    name = StringField(required=True)
    gender = StringField(required=False)
    phone_number = StringField(required=True)
    email = StringField(required=True)
    password = StringField(required=True)
    orders = ListField(required=False)
class Delivery(Document):
    species = StringField(required=True)
    name = StringField(required=True)
    gender = StringField(required=False)
    phone_number = StringField(required=True)
    email = StringField(required=True)
    password = StringField(required=True)
    identity = StringField(required=True)
    car_number = StringField(required=True)
    licence = StringField(required=True)
    orders = ListField(required=False)